-- 테이블: 도서정보, 저자정보, 판매량 정보
-- 2022년 1월
-- 저자별, 카테고리별 매출액
-- 저자 아이디 오름차순, 카테고리 내림차순

-- 날짜 필터링
-- 북아이디로 조인, 저자로 조인
-- 저자별, 카테고리별 그룹화

WITH BOOK_SALES_TOTAL AS (
    SELECT BOOK_ID, SUM(SALES) AS COUNT_SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY BOOK_ID
)

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.COUNT_SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES_TOTAL BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;