-- 3세대 대장균 id
-- id 오름차순
-- recursive

WITH RECURSIVE ECOLI_HIERARCHY AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, H.GENERATION + 1
    FROM ECOLI_DATA D
    JOIN ECOLI_HIERARCHY H ON D.PARENT_ID = H.ID
    WHERE H.GENERATION < 3
)

SELECT ID
FROM ECOLI_HIERARCHY
WHERE GENERATION = 3
ORDER BY ID;