-- 테이블: 상품 판매 정보
-- 동일한 회원이 동일한 상품을 재구매한 데이터
-- 회원 ID 오름차순, 상품 ID 내림차순

SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS C FROM ONLINE_SALE GROUP BY USER_ID, PRODUCT_ID) AS S
WHERE S.C > 1
GROUP BY USER_ID, PRODUCT_ID
ORDER BY USER_ID, PRODUCT_ID DESC;