-- 음식 종류별 즐겨찾기수 가장 많은 식당
-- 음식 종류 내림차순

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
           RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FAV_RANK
    FROM REST_INFO
) RANKED
WHERE FAV_RANK = 1
ORDER BY FOOD_TYPE DESC;