-- 크기에 따라 분류 크기 내림차순
-- 아이디 오름차순
-- PERCENT_RANK() OVER

-- 퍼센트 구하고 분기

WITH RANK_RESULT AS (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
    FROM ECOLI_DATA
)

SELECT ID,
    CASE
        WHEN SIZE_RANK <= 0.25 THEN 'CRITICAL'
        WHEN SIZE_RANK <= 0.5 THEN 'HIGH'
        WHEN SIZE_RANK <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANK_RESULT
ORDER BY ID;