-- 각 세대별 자식이 없는 개체의 수
-- 세대 오름차순

-- 세대 구하기
-- 각 세대별로 다른 대장균의 Parent_id에 없는 거 구하기
-- 정렬

WITH RECURSIVE ECOLI_HIERARCHY AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, H.GENERATION + 1
    FROM ECOLI_DATA D
    JOIN ECOLI_HIERARCHY H ON H.ID = D.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_HIERARCHY H
LEFT JOIN ECOLI_DATA D ON H.ID = D.PARENT_ID
WHERE D.PARENT_ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION;